
import java.awt.TextField;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.text.BreakIterator;
import java.util.List;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author damA
 */
public class PantallaSecundaria extends javax.swing.JDialog {
private PantallaPrincipal pp;
Conectar conectar= null;
    /**
     * Creates new form PantallaSecundaria
     */
    public PantallaSecundaria(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        lstDeportes.setVisible(false);
           
        conectar = new Conectar();
        Connection conexion=conectar.getConnection();
        if (conexion != null) {
            JOptionPane.showMessageDialog(this, "conexion establecida correctamente");
        }else{
            JOptionPane.showMessageDialog(this, "conexion no establecida");
        }
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupSexo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldProfesion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxEdad = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jSpinnerHermanos = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        jRadioButtonHombre = new javax.swing.JRadioButton();
        jRadioButtonMujer = new javax.swing.JRadioButton();
        jCheckBoxDeporte = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstDeportes = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSliderCompras = new javax.swing.JSlider();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSliderTelevision = new javax.swing.JSlider();
        jLabel9 = new javax.swing.JLabel();
        jSliderCine = new javax.swing.JSlider();
        jButtonAceptar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(229, 252, 250));
        jPanel1.setForeground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        jLabel1.setText("Profesión");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 19, -1, -1));
        jPanel1.add(jTextFieldProfesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 14, 120, 29));

        jLabel2.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        jLabel2.setText("Edad");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        jComboBoxEdad.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        jComboBoxEdad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Menos de 18 años", "Entre 18 y 30 años", "Más de 30 años" }));
        jPanel1.add(jComboBoxEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 136, -1));

        jLabel3.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        jLabel3.setText("Nº Hermanos");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 58, -1, -1));
        jPanel1.add(jSpinnerHermanos, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 57, -1, -1));

        jPanel2.setBackground(new java.awt.Color(229, 252, 250));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sexo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Leelawadee UI", 1, 12))); // NOI18N

        jRadioButtonHombre.setBackground(new java.awt.Color(229, 252, 250));
        buttonGroupSexo.add(jRadioButtonHombre);
        jRadioButtonHombre.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        jRadioButtonHombre.setText("Hombre");

        jRadioButtonMujer.setBackground(new java.awt.Color(229, 252, 250));
        buttonGroupSexo.add(jRadioButtonMujer);
        jRadioButtonMujer.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        jRadioButtonMujer.setText("Mujer");
        jRadioButtonMujer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMujerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonHombre)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonMujer)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonHombre)
                    .addComponent(jRadioButtonMujer)))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, -1));

        jCheckBoxDeporte.setBackground(new java.awt.Color(229, 252, 250));
        jCheckBoxDeporte.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        jCheckBoxDeporte.setText("¿Practicas algún deporte?");
        jCheckBoxDeporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxDeporteActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBoxDeporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 95, -1, -1));

        lstDeportes.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        lstDeportes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Cazar medusas", "Sofing", "Peseguir lineas", "Tirar de coches", "Golpear piedras", "Dar saltitos" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstDeportes.setSelectionBackground(new java.awt.Color(255, 102, 255));
        jScrollPane1.setViewportView(lstDeportes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 140, 87));

        jLabel5.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        jLabel5.setText("¿Cuál?");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 163, 640, 10));

        jSliderCompras.setBackground(new java.awt.Color(229, 252, 250));
        jSliderCompras.setFont(new java.awt.Font("Lato Semibold", 1, 12)); // NOI18N
        jSliderCompras.setForeground(new java.awt.Color(0, 0, 0));
        jSliderCompras.setMajorTickSpacing(1);
        jSliderCompras.setMaximum(10);
        jSliderCompras.setMinimum(1);
        jSliderCompras.setMinorTickSpacing(5);
        jSliderCompras.setPaintLabels(true);
        jSliderCompras.setPaintTicks(true);
        jSliderCompras.setSnapToTicks(true);
        jSliderCompras.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 204, 255)));
        jSliderCompras.setValueIsAdjusting(true);
        jPanel1.add(jSliderCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 340, -1));

        jLabel6.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        jLabel6.setText("Marque su grado de afición a :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 179, -1, -1));

        jLabel7.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        jLabel7.setText("Compras");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        jLabel8.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        jLabel8.setText("Ver la televisión");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jSliderTelevision.setBackground(new java.awt.Color(229, 252, 250));
        jSliderTelevision.setFont(new java.awt.Font("Lato Semibold", 1, 12)); // NOI18N
        jSliderTelevision.setForeground(new java.awt.Color(0, 0, 0));
        jSliderTelevision.setMajorTickSpacing(1);
        jSliderTelevision.setMaximum(10);
        jSliderTelevision.setMinimum(1);
        jSliderTelevision.setMinorTickSpacing(5);
        jSliderTelevision.setPaintLabels(true);
        jSliderTelevision.setPaintTicks(true);
        jSliderTelevision.setValue(5);
        jSliderTelevision.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 204, 255)));
        jSliderTelevision.setValueIsAdjusting(true);
        jPanel1.add(jSliderTelevision, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 340, -1));

        jLabel9.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        jLabel9.setText("Ir al cine");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 337, -1, -1));

        jSliderCine.setBackground(new java.awt.Color(229, 252, 250));
        jSliderCine.setFont(new java.awt.Font("Lato Semibold", 1, 12)); // NOI18N
        jSliderCine.setForeground(new java.awt.Color(0, 0, 0));
        jSliderCine.setMajorTickSpacing(1);
        jSliderCine.setMaximum(10);
        jSliderCine.setMinimum(1);
        jSliderCine.setMinorTickSpacing(5);
        jSliderCine.setPaintLabels(true);
        jSliderCine.setPaintTicks(true);
        jSliderCine.setSnapToTicks(true);
        jSliderCine.setValue(1);
        jSliderCine.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 204, 255)));
        jSliderCine.setValueIsAdjusting(true);
        jPanel1.add(jSliderCine, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 340, -1));

        jButtonAceptar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonAceptar.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, -1, -1));

        jButtonCancelar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCancelar.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 400, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonMujerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMujerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonMujerActionPerformed

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        // TODO add your handling code here:
       String profesion = "";
        if (jTextFieldProfesion.getText().length() != 0) {
            profesion = jTextFieldProfesion.getText();
            CrearUsuario(profesion);
        }else{
             JOptionPane.showMessageDialog(this,"Revisa el campo de la profesion","Profesion vacio",JOptionPane.ERROR_MESSAGE);  
        }
    }
    
    
    private void CrearUsuario(String profesion){
       String edad = jComboBoxEdad.getSelectedItem().toString();
       int hermanos =(Integer)jSpinnerHermanos.getValue();
       String sexo;
        if (jRadioButtonHombre.isSelected()) {
            sexo = "Hombre";
        }else {
            sexo = "Mujer";
        }
        boolean practicarDeporte ;
        String deporte="";
        if (jCheckBoxDeporte.isSelected()) {
            practicarDeporte= true;
       
       var des = lstDeportes.getSelectedValuesList();
       deporte = des.get(0);
            for (int i = 1; i < des.size(); i++) {
                deporte=deporte+ ", "+des.get(i);
            }
             
        }else{
            practicarDeporte = false;
            deporte= "";
        }
        
       
        int tv = (Integer)jSliderTelevision.getValue();
        int compras = (Integer)jSliderCompras.getValue();
        int cine = (Integer)jSliderCine.getValue();
        if (profesion.length()!=0) {
         
        PreparedStatement ps= null;
        String sql;
        Connection cone = conectar.getConnection();
        sql= "insert into usuarios(profesion,edad,hermanos,sexo,deportes,compras,television,cine)"
                + "values(?,?,?,?,?,?,?,?)";
            try {
               ps = cone.prepareStatement(sql);
               ps.setString(1,profesion);
               ps.setString(2, edad);
               ps.setInt(3, hermanos);
               ps.setString(4, sexo);
               ps.setString(5, deporte);
               ps.setInt(6, compras);
               ps.setInt(7, tv);
               ps.setInt(8, cine);
               ps.executeUpdate();
               JOptionPane.showMessageDialog(null, "Se han insertado los datos");

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        dispose();
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        dispose();       
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jCheckBoxDeporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxDeporteActionPerformed
        // TODO add your handling code here:
        if (jCheckBoxDeporte.isSelected()) {
            lstDeportes.setVisible(true);
        }else
        {
            lstDeportes.setVisible(false);
        }
    }//GEN-LAST:event_jCheckBoxDeporteActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupSexo;
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JCheckBox jCheckBoxDeporte;
    private javax.swing.JComboBox<String> jComboBoxEdad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButtonHombre;
    private javax.swing.JRadioButton jRadioButtonMujer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSlider jSliderCine;
    private javax.swing.JSlider jSliderCompras;
    private javax.swing.JSlider jSliderTelevision;
    private javax.swing.JSpinner jSpinnerHermanos;
    private javax.swing.JTextField jTextFieldProfesion;
    private javax.swing.JList<String> lstDeportes;
    // End of variables declaration//GEN-END:variables
}
